fix: Adding the first version of base-security-services-da
terraform-ibm-modules/terraform-ibm-base-security-services-da pull request #2
Opened 2024-02-21 01:36 UTC by tyao117

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-02-21 08:19 UTC, ocofaigh requested changes
see comments

2024-02-21 08:19 UTC, ocofaigh commented on main.tf
> +}
the terraform block should go into a file called `version.tf`. Also because this is a DA, and not a module, you should lock into an exact version. I suggest to lock into the latest (1.62.0), and we will create a renovate rule to bump the version with automated PRs as new versions come out.

2024-02-21 08:19 UTC, ocofaigh commented on main.tf
> +}
put the provider config into a file called provider.tf. Also use a variable for the region (var.region)

2024-02-21 08:19 UTC, ocofaigh commented on main.tf
> +}
What you have added in `./modules/security_services_base` is not a module, its a DA (since it contains a provider.tf file). A DA is not designed to be consumed in a module block, as it has several limitations. From [hashicorp docs](https://developer.hashicorp.com/terraform/language/modules/develop/providers):

> A module containing its own provider configurations is not compatible with the for_each, count, and depends_on arguments

I was suggest just adding the code directly in this main.tf file

2024-02-22 17:06 UTC, ocofaigh requested changes
see comments

2024-02-22 17:06 UTC, ocofaigh commented on main.tf
> +  cos_bucket        = local.cos_bucket_name_input
again I would expose `skip_cos_iam_authorization_policy` but call it `skip_cos_scc_auth_policy`

2024-02-22 17:06 UTC, ocofaigh commented on main.tf
> +  sm_service_plan      = "standard"
I think this should be exposed as a variable so teams can choose trial instance - its possible to update to standard so I think its good to expose to allow people to do a POC first with minimal cost, and then they can upgrade

2024-02-22 17:06 UTC, ocofaigh commented on main.tf
> +  service_endpoints    = "private"
You need to set `kms_encryption_enabled = true` and pass values for `existing_kms_instance_guid` and `kms_key_crn`. It means you will have to add new input variables for this in the DA inputs, and also update the code to create KMS key ring / key for these too

2024-02-22 17:06 UTC, ocofaigh commented on main.tf
> +  resource_group_id    = data.ibm_resource_group.resource_group.id
suggest exposing `enable_event_notification`, `existing_en_instance_crn` and `skip_en_iam_authorization_policy` (but perhaps call it `skip_en_sm_auth_policy`)

2024-02-22 17:06 UTC, ocofaigh commented on main.tf
> +  resource_group_id    = data.ibm_resource_group.resource_group.id
also set `endpoint_type = private`

2024-02-22 18:09 UTC, bhakta-ibm commented on variables.tf
> +  default     = null
Yes, we wanted to have it mandatory. For now input is fine. But Ideally, we should create an AT instance in not provided.

2024-02-22 19:46 UTC, ocofaigh commented on variables.tf
> +  default     = null
yea I think that is best approach here. Not a big deal to add now. You can use https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/tree/main/modules/activity_tracker to provision the instance

2024-02-22 19:48 UTC, ocofaigh commented on variables.tf
> +  default     = null
As per sysdig comment, I think we we should add code to create the AT instance if `null` is passed here. You can use https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/tree/main/modules/activity_tracker to do this

2024-02-22 21:10 UTC, tyao117 commented on main.tf
> +  cos_new_bucket_name   = join("-", [var.cos_bucket_name, resource.random_string.cos_bucket[0].id])
The random prefix is to prevent name collisions when using the default variable of COS. Because COS is a global instance, if the names are unique and distinct (each COS name have to be distinct from each other), the service would not be provisioned.

2024-02-22 21:10 UTC, tyao117 commented on main.tf
> +}
https://github.com/terraform-ibm-modules/terraform-ibm-base-security-services-da/pull/2#discussion_r1499940649

2024-02-22 21:17 UTC, tyao117 commented on data.tf
> +}
done in latest commits

2024-02-22 21:19 UTC, tyao117 commented on main.tf
> +module "key_protect_instance" {
done. i changed each module name to have a prefix to prevent name collision

2024-02-22 21:19 UTC, tyao117 commented on main.tf
> +  cos_instance_crn  = local.cos_instance_crn_input
implemented in the latest commit

2024-02-22 21:19 UTC, tyao117 commented on main.tf
> +  cos_bucket        = local.cos_bucket_name_input
done this in latest commit

2024-02-22 21:20 UTC, tyao117 commented on main.tf
> +  sm_service_plan      = "standard"
implemented new vars which default to using  the 'standard' plan but they can specify other plans.

2024-02-22 21:20 UTC, tyao117 commented on main.tf
> +  service_endpoints    = "private"
implemented in the latest commit

2024-02-22 21:21 UTC, ocofaigh commented on main.tf
> +  cos_new_bucket_name   = join("-", [var.cos_bucket_name, resource.random_string.cos_bucket[0].id])
No need to do this - the tests will use a random prefix for the instance names. I'm thinking that maybe we actually remove the default values for the instance name variables and make them required inputs

2024-02-22 21:21 UTC, tyao117 commented on main.tf
> +  resource_group_id    = data.ibm_resource_group.resource_group.id
setting the `endpoint_type = private` fails the terraform plan because Resource controller cannot verify that the instance is up.

2024-02-22 21:48 UTC, bhakta-ibm commented on main.tf
> +  resource_group_id    = data.ibm_resource_group.resource_group.id
You would have to run this from a system in IBM Cloud. From your office it will fail.

2024-03-11 16:40 UTC, ocofaigh commented
This has been replaced by individual DAs - closing this

2024-03-11 16:40 UTC, closed without merging